version: '3.8'

services:
  mariadb:
    restart: always
    build: ./requirements/mariadb
    container_name: db_ct
    image: mariadb
    env_file:
        ./.env
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    restart: always
    depends_on:
        - mariadb
    build: ./requirements/wordpress
    container_name: wp_ct
    image: wp
    env_file:
        ./.env
    volumes:
      - web_data:/home/ytouate/data/wordpress

  nginx:
    restart: always
    depends_on:
      - wordpress
      # - my_site
    build: ./requirements/nginx
    image: nginx
    container_name: nginx_ct
    ports:
      - 81:81
      - 443:443
    volumes:
      - web_data:/home/ytouate/data/wordpress
      - my_site_data:/my_site

  redis:
    restart: always
    container_name: redis_ct
    image: redis
    build:
      context: ./requirements/bonus
      dockerfile: redis.Dockerfile

  my_site:
    depends_on:
      - nginx
    container_name: my_site_ct
    build:
      context: ./requirements/bonus
      dockerfile: my_site.Dockerfile
    volumes:
      - my_site_data:/my_site

  ftp:
    container_name: ftp_ct
    image: ftp
    build:
     context: ./requirements/bonus
     dockerfile: ftp.Dockerfile
    env_file:
      - ./.env
    restart: always
    ports:
      - 21:21
    volumes:
        - web_data:/home/ytouate/data/wordpress

volumes:
  my_site_data:
  db_data:
    driver: local
    driver_opts:
      type: none
      device: /home/ytouate/data/mariadb
      o: bind
  web_data:
    driver: local
    driver_opts:
      type: none
      device: /home/ytouate/data/wordpress
      o: bind

networks:
  default:
