version: '3.8'

services:
  mariadb:
    build: ./requirements/mariadb
    container_name: db_ct
    image: mariadb
    env_file:
        ./.env
    restart: always
    volumes:
      - db_data:/var/lib/mysql
  wordpress:
    depends_on:
        - mariadb
    build: ./requirements/wordpress
    container_name: wp_ct
    image: wp
    volumes:
      - /home/ytouate/data/wordpress:/home/ytouate/data/wordpress
    env_file:
        ./.env
    restart: always
  nginx:
    depends_on:
      - wordpress
      - mariadb
    restart: always
    build: ./requirements/nginx
    image: nginx
    container_name: nginx_ct
    ports:
      - 443:443
    volumes:
      - /home/ytouate/data/wordpress:/home/ytouate/data/wordpress
volumes:
  db_data:
networks:
  default: