version: '3.8'

services:
  mariadb:
    restart: always
    build: ./requirements/mariadb
    container_name: db_ct
    image: mariadb
    env_file:
        ./.env
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    restart: always
    depends_on:
        - mariadb
    build: ./requirements/wordpress
    container_name: wp_ct
    image: wp
    env_file:
        ./.env
    volumes:
      - web_data:/home/ytouate/data/wordpress

  nginx:
    restart: always
    depends_on:
      - wordpress
    build: ./requirements/nginx
    image: nginx
    container_name: nginx_ct
    ports:
      - 443:443
    volumes:
      - web_data:/home/ytouate/data/wordpress
      - static_site_data:/static_site

  redis:
    restart: always
    container_name: redis_ct
    image: redis
    build: ./requirements/bonus/redis

  static_site:
    depends_on:
      - nginx
    container_name: static_site_ct
    ports:
      - 81:81
    build: ./requirements/bonus/static_site
    volumes:
      - static_site_data:/static_site

  ftp:
    container_name: ftp_ct
    init: true
    image: ftp
    build: ./requirements/bonus/ftp
    env_file:
      - ./.env
    restart: always
    ports:
      - 21:21
      - 20:20
    volumes:
        - web_data:/home/ytouate/data/wordpress
  adminer:
    container_name: adminer_ct
    image: adminer
    build: ./requirements/bonus/adminer
    ports:
      - 82:82

  ctop:
    tty: true
    container_name: ctop_ct
    image: ctop
    restart: always
    build: ./requirements/bonus/ctop
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  static_site_data:
  db_data:
    driver: local
    driver_opts:
      type: none
      device: /home/ytouate/data/mariadb
      o: bind

  web_data:
    driver: local
    driver_opts:
      type: none
      device: /home/ytouate/data/wordpress
      o: bind

networks:
  default:
